# Generated by Django 4.2.3 on 2024-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materilas', '0004_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
    ]
