# Generated by Django 4.2.3 on 2024-03-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
